from __future__ import annotations

import threading

from common import default_data_dir, default_persist_dir
from core.collection_manifest import (
    COLLECTION_CONFIGS,
    COLLECTION_MANIFEST_PATH,
    COMPATIBILITY_BUNDLE_CONFIG,
    DEFAULT_COLLECTION_KEY,
    DEFAULT_RUNTIME_COLLECTION_KEYS,
)

PERSIST_DIR = str(default_persist_dir())
DATA_DIR = str(default_data_dir())
DEFAULT_EMBEDDING_MODEL = "BAAI/bge-m3"
EMBEDDING_MODEL_ENV_KEY = "DOC_RAG_EMBEDDING_MODEL"
EMBEDDING_MODEL = DEFAULT_EMBEDDING_MODEL
SEARCH_K = 3
SEARCH_FETCH_K = 10
SEARCH_LAMBDA = 0.3
CHUNK_SIZE = 800
CHUNK_OVERLAP = 120
MAX_QUERY_COLLECTIONS = 2
DEFAULT_QUERY_TIMEOUT_SECONDS = 30
DEFAULT_MAX_CONTEXT_CHARS = 1500
COLLECTION_SOFT_CAP = 30_000
COLLECTION_HARD_CAP = 50_000
ADMIN_CODE_ENV_KEY = "DOC_RAG_ADMIN_CODE"
AUTO_APPROVE_ENV_KEY = "DOC_RAG_AUTO_APPROVE"
CHUNKING_MODE_ENV_KEY = "DOC_RAG_CHUNKING_MODE"
CHUNK_TOKEN_ENCODING_ENV_KEY = "DOC_RAG_CHUNK_TOKEN_ENCODING"
QUERY_TIMEOUT_SECONDS_ENV_KEY = "DOC_RAG_QUERY_TIMEOUT_SECONDS"
MAX_CONTEXT_CHARS_ENV_KEY = "DOC_RAG_MAX_CONTEXT_CHARS"
UPLOAD_REQUEST_STORE_FILE = "upload_requests.json"
REQUEST_STATUS_PENDING = "pending"
REQUEST_STATUS_APPROVED = "approved"
REQUEST_STATUS_REJECTED = "rejected"
REQUEST_STATUSES = {REQUEST_STATUS_PENDING, REQUEST_STATUS_APPROVED, REQUEST_STATUS_REJECTED}
UPLOAD_REQUEST_LOCK = threading.RLock()
COLLECTION_NAME = str(COLLECTION_CONFIGS[DEFAULT_COLLECTION_KEY]["name"])
COUNTRY_BY_COLLECTION_KEY = {
    key: str(config.get("default_country", "all"))
    for key, config in COLLECTION_CONFIGS.items()
}
